stages:
  - build
  - test

before_script:
  - docker info
  - pip install -r requirements.txt
  - export PATH=$PATH:/usr/local/go/bin

build_runcmd:
  image: registry.gitlab.com/jarv/cmdchallenge-ci-image
  stage: build
  script:
    - make build-runcmd

build_docker_image:
  image: registry.gitlab.com/jarv/cmdchallenge-ci-image
  stage: build
  script:
    - make build-docker

test_runcmd:
  image: registry.gitlab.com/jarv/cmdchallenge-ci-image
  stage: test
  script:
    - make test-runcmd

test_challenges:
  image: registry.gitlab.com/jarv/cmdchallenge-ci-image
  stage: test
  script:
    - make build-docker
    - make test-challenges
