stages:
  - build
  - test

before_script:
  - docker info
  - apt-get update
  - apt-get install -y make python-pip
  - pip install -r requirements.txt

build_docker_image:
  image: gitlab/dind
  stage: build
  script:
    - make docker

test_challenges:
  image: gitlab/dind
  stage: test
  script:
    - make test
