stages:
  - build

before_script:
  - docker info
  - apt-get update
  - apt-get install -y make python-pip
  - pip install -r requirements.txt

build:
  image: gitlab/dind
  stage: build
  script:
    - make
